# Generated by Django 5.2.11 on 2026-02-14 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyaccess',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='emergencyaccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencyaccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
