# Generated by Django 5.2.11 on 2026-02-14 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consent',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('patient', 'provider', 'record_type')},
        ),
    ]
