# Generated by Django 5.2.11 on 2026-02-14 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_logs', '0001_initial'),
        ('medical_records', '0002_alter_medicalrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
